dist: trusty
services: docker
sudo: required
language: rust
rust:
  - stable

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - CRATE_NAME=ruuvitag-listener

matrix:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=x86_64-unknown-linux-gnu

before_install:
  - set -e
  - sudo gem install fpm
  - rustup self update

install:
  - cargo install cross --force

script:
  - sh ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "MngTTYpAr5BFg5hACoKgSc+zAweydtpUoPllC2pjPpZQKc07qKlV9R3VWVmHcOy1r284xCj5AbveQQBqq2TUlC6Al4AU+yacz8t6YsEAdP9Vxjo7g+mYYfPN+7mmuZ911zklamY0jGSy+yFmsMz65shl0f/4GmFIVWwFFbCEz8g+PoyMov3KziujEm3Ohp/ta3clMkUPeCfqI+uaavdQQIhilx8V8hAGjhcAKRhHkHlqjY84pm6tATa33HctqA9jp9dZjmYKCClYdng+NONAsfgEhsg6qADHyc2vSVbfugJFFSUoRNgrH/ZLI9/vKYGVzKQvezwsO28n6Wa7lto+8ybWgpMDMMRCO9f+wUXpTgB4bcBRuWT33IZ9IF3clJIl1Az94Rgd7W8YDZxd/djSsEGAQ5uJD+xIbfXkoBswjQ6FmSSRm7gKkQJQ62Q8DV9aR2ujB5LQ+opjNiretCjQz754cAeIlJ1uXOO2K/N3nnpuhZBH8i91Au4SqurwhmCcbkUWTYEiyjfKwzbyAjgsCwQSwNfDuKPtSGQbvHtlGN37Gu7j6k7+CNOzLX18BJ/IS5jEy/wJegg3P0HcaO51HFSkYzUeYl2pinIjvj9tBBLQPLZpIeJSxuseso3QzDm98ByMbwOAj4Iw2lTgWOU2+C2zzQlkaX0aCiCnjjD76pc="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    repo: lautis/ruuvitag-listener
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true

  provider: releases
  skip_cleanup: true
