[target.aarch64-unknown-linux-gnu.dockerfile]
file = ".github/docker/cross.Dockerfile"
context = "."
build-args = { CROSS_DEB_ARCH = "arm64", PKG_CONFIG_LIBDIR = "/usr/lib/aarch64-linux-gnu/pkgconfig" }

[target.armv7-unknown-linux-gnueabihf.dockerfile]
file = ".github/docker/cross.Dockerfile"
context = "."
build-args = { CROSS_DEB_ARCH = "armhf", PKG_CONFIG_LIBDIR = "/usr/lib/arm-linux-gnueabihf/pkgconfig" }

[build.env]
passthrough = ["RUST_BACKTRACE"]
